# Generated by Django 3.2 on 2022-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('admin', 'admin')], max_length=100),
        ),
    ]
