# Generated by Django 3.2 on 2022-01-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_board_board_list_list_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.board')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.userprofile')),
            ],
        ),
    ]
