# Generated by Django 3.2 on 2022-02-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_add_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.board')),
            ],
        ),
        migrations.CreateModel(
            name='Card_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.board_card')),
            ],
        ),
        migrations.RemoveField(
            model_name='list_card',
            name='list',
        ),
        migrations.DeleteModel(
            name='Board_List',
        ),
        migrations.DeleteModel(
            name='List_Card',
        ),
    ]
