# Generated by Django 3.2 on 2022-02-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0005_auto_20220203_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_list',
            old_name='list',
            new_name='card',
        ),
    ]
